apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: raph37/learning_microservices_auth

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  # we are not specifying a type but ipconfig is the default service
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
